<?php

//Creates a menu for the DNA Generator
function dna_generator_menu() {
    $items = [];
    $items['dna_generator'] = array(
        'title' => 'DNA Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_generator_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

//Form created by drupal
function dna_form() {
    $form['dna_value'] = array(
        '#title' => 'Value',
        '#type' => 'textfield',
        '#description' => t('Enter in your first helix of your DNA and watch it generate the second!'),
        '#element_validate' => array('element_validate_dna'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );
    return $form;
}

//Verifying that there is a element validation
function element_validate_dna($element) {
    $user_input = explode(' ', strtoupper($element['#value']));
    foreach ($user_input as $value) {
        if(!($value == 'A' || $value == 'T' || $value == 'C' || $value == 'G')) {
            form_error($element, t('Please enter A, T, C, or G'));
        }
    }
}

//Function created in order to verify that each letter will choose the corresponding letter
function helix($input) {
    $user_input = explode(' ', $input);
    $output_helix = [];
    foreach($user_input as $letter) {
        if ($letter == 'A') {
            array_push($output_helix, 'T');
        } elseif($letter == 'T') {
            array_push($output_helix, 'A');
        } elseif ($letter == 'C') {
            array_push($output_helix, 'G');
        } elseif ($letter == 'G') {
            array_push($output_helix, 'C');
        }
    }
    return $output_helix;
}

//Saves the user input and runs it through the helix function
function dna_form_submit($form, &$form_state) {
    $user_input = strtoupper($form_state['values']['dna_value']);
    $result = helix($user_input);
    $_SESSION['output_dna'] = $result;
    $form_state['redirect'] = 'dna_generator_success_page';
}

//Produces each letter on its on seperate line
function dna_success() {
    $output = '<div>';
    foreach ($_SESSION['output_dna'] as $letter) {
        $output = $output . '<p>' . $letter . '</p>';
    }
    $output = $output . '</div>';

    return $output;
}
