<?php

function mymodule_menu() {
    $items['path-to-ajax/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'mymodule_ajax_callback',
        'page arguments' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function mymodule_ajax_callback($js, $node_id) {
    $node = node_load($node_id);

    if($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    //Get the render array for the node, and render it into actual HTML
    $build = node_view($node);
    $html = render($build);

    //Here we prepare an ajax command to insert he node's HTML into out div under News - the wrapper.
    $commands = array();
    $commands[] = ajax_command_html('#mymodule-ajax-wrapper', $html);

    //Render the commands into JSON data form and execute them by printing them to the browser.
    print ajax_render($commands);
    exit; //Exit so Drupal doesn't hace a chance to build a whole page.
}
